#!/usr/bin/env python3
"""Generate a compact GB2312/GBK (EUC, two-byte area 0xA1-FE x 0xA1-FE) ->
Unicode BMP lookup header used by ProgramGuide to decode Chinese EPG/service
names without iconv.

The two-byte box 0xA1-FE x 0xA1-FE covers the whole GB2312 charset plus the
GBK punctuation/symbol re-mappings broadcasters actually use (e.g. A1A4 for
U+00B7 middle dot, A1AA for U+2014 em dash), so a 94x94 grid is sufficient.
Index with (hi-0xA1)*94+(lo-0xA1); 0 means unassigned.  All code points here
fit in the BMP, so each cell is a uint16_t.
"""
import sys

ROWS = 0xFE - 0xA1 + 1  # 94
COLS = 0xFE - 0xA1 + 1  # 94


def main(out_path):
    grid = [[0] * COLS for _ in range(ROWS)]
    multi = 0
    astral = 0
    for hi in range(0xA1, 0xFF):
        for lo in range(0xA1, 0xFF):
            raw = bytes((hi, lo))
            try:
                text = raw.decode('gbk')
            except UnicodeDecodeError:
                continue
            if len(text) != 1:
                multi += 1
                continue
            cp = ord(text)
            if cp > 0xFFFF:
                astral += 1
                continue
            grid[hi - 0xA1][lo - 0xA1] = cp

    lines = [
        '// Generated by tools/gen_gb2312_tab.py. Do not edit.',
        '#pragma once',
        '#include <cstdint>',
        '',
        'namespace lme2510 {',
        'namespace detail {',
        '',
        '// Two-byte GB2312/GBK box (0xA1..0xFE x 0xA1..0xFE) to Unicode BMP.',
        '// Index with (hi-0xA1)*94+(lo-0xA1); 0 means unassigned.',
        'inline constexpr std::uint16_t kGb2312ToUnicode[94][94] = {',
    ]
    for row in grid:
        body = ','.join('0x%04X' % cp for cp in row)
        lines.append('    {%s},' % body)
    lines += [
        '};',
        '',
        '}  // namespace detail',
        '}  // namespace lme2510',
        '',
    ]
    with open(out_path, 'w', encoding='ascii') as out:
        out.write('\n'.join(lines))
    assigned = sum(1 for row in grid for cp in row if cp)
    print('wrote %s: %d/%d cells assigned (multi=%d astral=%d)'
          % (out_path, assigned, ROWS * COLS, multi, astral))


if __name__ == '__main__':
    main(sys.argv[1])
